# mkdocs.yml
# Configuration file for MkDocs (Automated project documentation generator)

site_name: Civic Lib Core
site_url: https://civic-interconnect.github.io/civic-lib-core/
repo_url: https://github.com/civic-interconnect/civic-lib-core
site_description: Core library for Civic Interconnect projects.
site_author: Civic Interconnect
docs_dir: docs
site_dir: site

extra:
  version:
    provider: mike

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections # Group navigation items
    - navigation.top # Back-to-top button
    - search.suggest # Search suggestions as you type
    - search.highlight # Highlight search terms
    - content.code.copy # Copy button on code blocks
    - toc.follow # Highlight current section in TOC

  palette:
    - scheme: default # Light/dark mode toggle
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true # Include module names
            show_root_toc_entry: true # Include module in TOC
            docstring_style: google # Professional docstring format
            show_signature_annotations: true
            separate_signature: true    # Makes function signatures easier to read

markdown_extensions:
  - admonition # Note/Warning/Tip boxes
  - codehilite # Syntax highlighting
  - tables # Markdown tables
  - toc:
      permalink: true # Clickable headers
      toc_depth: 3
  - pymdownx.superfences # Code blocks with syntax highlighting
  - pymdownx.details # Collapsible sections
  
nav:
  - User Guide:
      - Home: index.md
      - CLI: cli.md
  - Developer Guide:
      - API: api.md
      - Workflow: DEVELOPER.md
  - API Reference:
      - API Overview: api.md
      - CLI:
          - api/civic_lib_geo.cli.cli.md
          - api/civic_lib_geo.cli.check_size.md
          - api/civic_lib_geo.cli.chunk_geojson.md
          - api/civic_lib_geo.cli.read_props.md
          - api/civic_lib_geo.cli.shapefile_to_geojson.md
          - api/civic_lib_geo.cli.simplify_geojson.md
          - api/civic_lib_geo.cli.topojson_to_geojson.md
      - Utilities:
          - api/civic_lib_geo.fips_utils.md
          - api/civic_lib_geo.geojson_utils.md
          - api/civic_lib_geo.shapefile_utils.md
          - api/civic_lib_geo.topojson_utils.md
          - api/civic_lib_geo.us_constants.md
