name: Civic Interconnect Library Tests (GIS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel --prefer-binary
          python -m pip install --upgrade -r requirements-dev.txt --timeout 100 --no-cache-dir

      - name: Check code formatting with Ruff
        run: |
          ruff format --check .

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest --cov=civic_lib_geo tests/
